README.md

chore: update travis-ci button

---

.github/CODEOWNERS

chore: fix codeowners file

---

package.json
packages/discovery-react-components/package.json
packages/discovery-react-components/src/components/SearchInput/__tests__/SearchInput.test.tsx
packages/discovery-styles/package.json
yarn.lock

Update package dependencies
Run the example app and make sure existing functionality is unaffected.
No

chore: Update dependencies

---

packages/discovery-react-components/src/components/SearchResults/components/Result/__tests__/Result.test.tsx
packages/discovery-styles/scss/components/search-results/_search-results.scss

Cleanup the unneeded styles and mock data

chore(SearchResults): cleanup

---

.github/CONTRIBUTING.md
.gitignore
.travis.yml
README.md
commitlint.config.js
lerna.json
package.json
packages/discovery-react-components/src/components/CIDocument/CIDocument.tsx
yarn.lock

adds deploy logic into our CI builds on master
- `develop` will do beta releases
- manually, we will do regular releases by creating a `release/whatever` branch and publishing that, then merging it back into `develop`
when this is merged into master, new PRs merged into `develop` should publish beta packages
should already be documented in the README
No

chore: add deploy logic back to travis

---

package.json
yarn.lock

chore: update/remove babel packages

---

.eslintrc
package.json
yarn.lock

adds the missing storybook dependencies

chore: add missing storybook dependencies

---

package.json

forgot to add this in when doing the eslint changes

chore: update eslint husky command for plugin resolve

---

packages/discovery-react-components/rollup.config.js

removes these warnings on `yarn workspace @ibm-watson/discovery-react-components run build`
```
(!) Plugin node-resolve: preferring built-in module 'events' over local alternative at '/Users/andrewturgeon/Dev/github.com/watson-developer-cloud/discovery-components/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Plugin node-resolve: preferring built-in module 'url' over local alternative at '/Users/andrewturgeon/Dev/github.com/watson-developer-cloud/discovery-components/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Plugin node-resolve: preferring built-in module 'punycode' over local alternative at …
```

chore: preferBuiltins false for rollup config

---

.travis.yml

makes it so `january_fix_pack` gets built on PR submission
make sure travis builds
no
no

chore: add january_fix_pack to buildable branches

---

packages/discovery-react-components/src/components/CIDocument/__stories__/default.md

Add documentation to CIDocument component
N/A
Yes
No

docs: add documentation for CI Document

---

packages/discovery-react-components/src/components/CIDocument/__stories__/default.md

Update CI Document documentation
N/A
Yes
No

fix: udpate CI Document documentation

---

README.md
examples/discovery-search-app/scripts/runExampleApp.sh
examples/discovery-search-app/scripts/serverSetup.sh
runExampleApp.sh

Add interactive script for configuring and building example application. Also prompts user asking if they'd like to start the example app.

chore: add script to setup and run example app

---

.travis.yml

Support release branches, following our [Branch and Releasing](https://github.com/watson-developer-cloud/discovery-components#branching-and-releasing) guidelines in the README.
Fixes https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/1166
???
Already handled in README.
Nyet

fix: support release branches

---

.travis.yml

Publish release candidates from `release/*` branches.

chore: add section to publish RC release from release branches

---

packages/discovery-react-components/src/components/DiscoverySearch/DiscoverySearch.tsx
packages/discovery-react-components/src/components/SearchFacets/SearchFacets.tsx
packages/discovery-react-components/src/components/StructuredQuery/StructuredQuery.tsx
packages/discovery-react-components/src/utils/useDataApi.ts

Remove need to disable linting check for `useEffect` dependencies when it comes to callbacks.

fix: callbacks optimizations

---

examples/discovery-search-app/cypress/integration/passages/spec.ts
package.json
yarn.lock

Upgrade Cypress (and related deps) to match tooling.
No

fix: update cypress and related dependencies

---

examples/discovery-search-app/cypress/integration/dynamic_facets/spec.ts
examples/discovery-search-app/cypress/integration/passages/spec.ts

Consolidate `dynamic_facets` test file as per Cypress best practices. Hopefully will fix test flakiness (and speed it up).
Run Cypress tests

test: consolidate to improve speed and flakiness

---

README.md

This adds more info to our README documentation on how to configure and use Discovery Components with Watson Discovery.
You can read through and see if this clearly communicates how to use Discovery Components with Watson Discovery.
Yes
No

docs: add info to README for improving and customizing components

---

.travis.yml
examples/discovery-search-app/package.json
package.json
packages/discovery-react-components/package.json
yarn.lock

`yarn audit` now exists and will report the audit problems we may see

fix: dompurify upgrade

---

README.md

docs: update README badge

---

packages/discovery-react-components/package.json
yarn.lock

Increases the version of lodash our components depend on to remedy a vulnerability.
Use `yarn list --production` to double-check that we're using version `4.17.21`

chore: upgrade lodash version

---

docs/components/components.md
docs/components/custom_components.md

Add an example for creating a custom component.
Update example app as specified in the docs.

docs: example for creating a custom component

---

docs/components/components.md
docs/components/custom_components.md
docs/getting-started/getting-started.md

docs: remove permalinks

---

packages/discovery-react-components/package.json
yarn.lock

Update to more recent version of Carbon resources

chore: update Carbon to 10.46.0/7.46.0

---

yarn.lock

Update yarn.lock for previous Carbon update change

Update yarn.lock for `chore: update Carbon to 10.46.0/7.46.0`

---

yarn.lock

Update some vulnerable deps to fix [issues found by dependabot](https://github.com/watson-developer-cloud/discovery-components/security/dependabot?q=is%3Aopen+sort%3Aseverity).

chore: update some vulnerable deps

---

.github/CODEOWNERS
yarn.lock

chore: update CODEOWNERS

---

yarn.lock

Commit changes that happen automatically when `yarn install` runs -- related to @agusev's most recent changes.
N/A
N/A
No

chore: updates to yarn.lock from latest changes

---

packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewer.tsx
yarn.lock

- make sure Worker is defined before trying to create one

fix: use Worker guard to fix unit tests

---

packages/discovery-styles/scss/components/search-results/_search-results.scss
yarn.lock

- add padding of 0 for left and right of passage

fix: remove horizontal padding from passages

---

packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewer.tsx
yarn.lock

- Add try / catch blocks with error logging when loading pdfs and pages

chore: add pdf error logging

---

yarn.lock

Last PR did not have all the lockfile changes, causing build failure. Ran yarn and added lockfile changes here.

chore: commit latest lockfile changes

---

packages/discovery-react-components/src/components/DiscoverySearch/__stories__/DiscoverySearch.stories.tsx
packages/discovery-react-components/src/components/SearchResults/__tests__/SearchResults.test.tsx
packages/discovery-react-components/src/utils/__tests__/useDataApi.test.tsx
yarn.lock

- Use ts-expect-error to be told when it's no longer necessary
N/A, as long as checks pass.
N/A
None

chore: replace ts-ignore with ts-expect-error

---

README.md
examples/discovery-search-app/package.json
package.json
packages/discovery-react-components/package.json
packages/discovery-react-components/src/components/CIDocument/components/Section/__fixtures__/sectionData.ts
packages/discovery-react-components/src/components/DiscoverySearch/DiscoverySearch.tsx
packages/discovery-react-components/src/components/DocumentPreview/__fixtures__/jsonPassages.ts
packages/discovery-react-components/src/components/DocumentPreview/__stories__/DocumentPreview.stories.tsx
packages/discovery-react-components/src/components/DocumentPreview/components/Highlight/passages.ts
packages/discovery-react-components/src/components/ResultsPagination/__fixtures__/searchResults.ts
packages/discovery-react-components/src/components/StructuredQuery/utils/stringifyStructuredQuerySelection.ts
packages/discovery-react-components/src/utils/useDeepCompareMemoize.ts
packages/discovery-styles/package.json
yarn.lock

Update peer-dependencies to match current pkg versions.
Fixes #491
Fixes #431 
Fixes #479

chore: update peer deps

---

README.md

A missing dot has been added, in order to demo:
* IBM + OpenSource relationship 
* Ways to contribute to IBM, which everybody can use
For more read here: https://www.meetup.com/togetherweopensource/
Open the README.md and check
No need - the change is simple

fix: add a missing dot

---

README.md

Add instructions for installing OS-level dependencies required for building `cairo` NPM package.

docs: add cairo deps

---

.github/workflows/ci.yaml
package.json
yarn.lock

Removes a lerna arg that is no longer needed.
Updates some deps.
Really, this is just a small change in order to kick off another release on master, since the previous one failed due to auth error (expired token).

ci: remove no longer needed lerna arg

---

packages/discovery-react-components/package.json
yarn.lock

Update version of disco-styles peerDependencies.
Update pkg resolutions to pick up vulnerability fixes (as found by dependabot).

chore: fix peerDependencies listing for disco-styles
