watson-developer-cloud/discovery-components

- examples/discovery-search-app/package.json
accidentally got up to `5.0.0` for some reason in the `discovery-search-app`
`npx lerna version` should no longer generate major version changes in the example app
no
> chore: update version in discovery-search-app

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
- .github/ISSUE_TEMPLATE/question.md
This adds `name` and `about` to our ISSUE_TEMPLATEs so that they will show up as options when new issues are created.
See that this is the requirement specified here: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
N/A
No
> fix: add name and about YAML to ISSUE_TEMPLATEs

- packages/discovery-react-components/src/components/SearchResults/__fixtures__/searchResults.ts
- packages/discovery-react-components/src/components/SearchResults/components/Result/Result.tsx
- packages/discovery-react-components/src/components/SearchResults/components/Result/__tests__/Result.test.tsx
- packages/discovery-react-components/src/components/SearchResults/utils/getDisplaySettings.ts
- packages/discovery-styles/scss/components/search-results/_search-results.scss
This changes the result title fallback. Also this will make it so that result titles and collection names will be cut off with `...` if they begin to overflow. See this gif
related to issue: https://github.ibm.com/Watson-Discovery/disco-widgets/issues/423 and https://github.ibm.com/Watson-Discovery/wd-issues/issues/1180
You can test this by starting storybook and changing the value of `title` to be any large value inside of `packages/discovery-react-components/src/components/SearchResults/__fixtures__/searchResults.ts`. Next open the SearchResults component and change the value of `resultTitleField` to be `title`. The title being displayed should be cutoff and `...` should be appended. You can do the same with `name` inside of `collectionsResponse.ts`
Also see the description of …
> fix(SearchResults): title fallback and footerbar value max length

- packages/discovery-react-components/src/components/CIDocument/components/CIDocument/__tests__/CIDocument.spec.tsx
This is a quick fix change to the CIDocument test, to prevent it from failing.  The default timeout for jest is 5000, which doesn't seem to be enough time to pass the test consistently.  This changes the timeout to 10000
Run `yarn test` and see that the CIDocument test `renders without crashing` passes.
> fix: cidocument test quickfix

- packages/discovery-react-components/src/components/CIDocument/components/CIDocument/__tests__/CIDocument.spec.tsx
Fixes the CIDocument test to account for future dependency changes
In discovery-react-components:
run `yarn test` and see that all tests pass
> fix: cidocument test issue

- packages/discovery-react-components/package.json
we weren't getting tags published due to a `git commit --amend` in the `postversion` lifecycle hook. this throws off the tagging branch and discards the tags.
this SO explains the problem https://stackoverflow.com/questions/34891663/how-to-update-the-git-tag-automatically-when-i-do-a-commit-amend/34892535#34892535
instead we should just `git add` files from the storybook build into the `version` lifecycle hook so that we don't delete tags
```
npx lerna version --conventional-prerelease --preid beta --dist-tag beta --no-push
```
^ adding `--no-push` let's you test the command without pushing to the repo accidentally
this should add tags to the repo again
N/A
No
> chore: fix postversion command

- packages/discovery-react-components/src/components/CIDocument/components/CIDocument/CIDocument.tsx
- packages/discovery-react-components/src/components/CIDocument/types.ts
- packages/discovery-react-components/src/utils/document/__tests__/processDoc.spec.tsx
- packages/discovery-react-components/src/utils/document/processDoc.ts
No longer add any data to the document input JSON object. - Duplicate of PR 13 
https://github.com/watson-developer-cloud/discovery-components/pull/13  - to add that in januaryfixpack branch. 
https://github.ibm.com/Watson-Discovery/docviz-squad-issue-tracker/issues/195
https://github.ibm.com/Watson-Discovery/wd-issues/issues/1365
Linked this repo up to `discovery-tooling` and saw that these changes fixed the issue noted above (and in the linked issues).
N/A
No
> fix: pr to add PR13 into janFixpack branch

- README.md
- packages/discovery-react-components/package.json
Existing `yarn code-coverage` command doesn't work since it directly uses `jest`. Instead, we need to go through `react-scripts` to properly set the environment. Add a `yarn test:coverage` command to handle this.
Run `yarn test:coverage`
Yes
> fix: use react-scripts to run with code-coverage

- packages/discovery-react-components/src/components/DiscoverySearch/DiscoverySearch.tsx
- packages/discovery-react-components/src/components/DiscoverySearch/__tests__/DiscoverySearch.test.tsx
- packages/discovery-react-components/src/components/DiscoverySearch/types.ts
- packages/discovery-react-components/src/components/StructuredQuery/StructuredQuery.tsx
- packages/discovery-react-components/src/components/StructuredQuery/__stories__/StructuredQuery.stories.tsx
- packages/discovery-react-components/src/components/StructuredQuery/__tests__/StructuredQuery.test.tsx
- packages/discovery-react-components/src/components/StructuredQuery/components/RuleRow/RuleRow.tsx
- packages/discovery-react-components/src/components/StructuredQuery/messages.ts
- packages/discovery-react-components/src/components/StructuredQuery/utils/__tests__/getFieldNames.test.ts
- packages/discovery-react-components/src/components/StructuredQuery/utils/getFieldNames.ts
- packages/discovery-react-components/src/utils/__tests__/useDataApi.test.tsx
- packages/discovery-react-components/src/utils/storybookUtils.tsx
- packages/discovery-react-components/src/utils/useDataApi.ts
This implements the `useFieldsApi` in order to fetch project fields and display them in our StructuredQuery component.
https://github.ibm.com/Watson-Discovery/disco-widgets/issues/184
You can verify this change by
1) Making sure the new unit tests added to `useDataApi.test.tsx`, `StructuredQuery.test.tsx`, and `DiscoverySearch.test.tsx` all pass and capture the intended functionality.
2) Making sure that the fields dropdown in storybook works as expected.
3) adding `StructuredQuery` to our example app (haven't added it yet since it's functionality is not complete) and checking that fields populate in the **Fields** dropdown menu
I've added this component to our storybook
No
> feat: implement fields api and use it in StructuredQuery

- packages/discovery-react-components/src/components/StructuredQuery/StructuredQuery.tsx
This fixes the bug that was previously merged due to our ESLint rules automatically adding `fetchFields` as a dependency to the useEffect hook which is in charge of calling it. This previously caused us to be in a loop of indefinitely calling `fetchFields`
- Load up storybook and open the `StructuredQuery` component. Notice that `fetchFields` only gets called once
n/a
no
> fix: endless fetch loop caused by eslint

- packages/discovery-react-components/src/components/CIDocument/components/CIDocument/CIDocument.tsx
- packages/discovery-react-components/src/components/CIDocument/components/CIDocument/__tests__/CIDocument.spec.tsx
- packages/discovery-react-components/src/components/CIDocument/components/FilterPanel/FilterPanel.tsx
- packages/discovery-react-components/src/components/CIDocument/components/NavigationToolbar/NavigationToolbar.tsx
- packages/discovery-react-components/src/utils/document/documentUtils.ts
- Add `data-testid` attributes to items that are used in document details integration tests
> chore: add test ids for use in discovery-tooling integration tests

- packages/discovery-react-components/src/components/DocumentPreview/DocumentPreview.tsx
- packages/discovery-react-components/src/components/DocumentPreview/__tests__/DocumentPreview.test.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/SimpleDocument/SimpleDocument.tsx
- packages/discovery-react-components/src/components/DocumentPreview/utils/__tests__/documentData.test.ts
- packages/discovery-react-components/src/components/DocumentPreview/utils/documentData.ts
When displaying the text for a uploaded JSON file, the selected field from DocumentPreview no longer defaults to HTML. It now will check for passage highlighting, then a specified body field, then a text field. If none of those are present, the error message appears. 
**This covers two issues:**
https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/1189
https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/1193
**Previously**, HTML would be the default view for processed JSON files, but the HTML field would not be rendered.
**Previously**, a specified body field would default to HTML view instead.
**Now**, the same document will default to the `text` field and display that text.
**Now**, the same document will also display a specified body field.
Run …
> fix: better JSON doc handling for DocumentPreview

- packages/discovery-styles/scss/components/search-facets/_search-facets.scss
Fixes the text wrapping in search facet tags. 
**Before:**
**After:**
https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/1245
1. Link components and tooling by running `yarn link-components` in tooling.
2. Link components-styles by running `yarn link` there and `yarn link @ibm-watson/discovery-styles` in tooling.
3. Select 10+ search filters in the Search Facets Panel
No
> bug: search facet tag text wrapping

- .travis.yml
- README.md
Updates documentation around using `master` for ongoing development and removing `develop`. There will be follow-up issues to:
- add compatibility tables between releases of Watson Discovery on CP4D and this component library
- switch lerna config to use single-version increments (instead of independent)
- publish docs to `gh_pages` branch instead of `master /docs`
Make sure that merging to `master` still triggers `beta`-style releases
Yes
`develop` branch no longer exists
> docs: update to use 'master' instead of 'develop'

- lerna.json
- packages/discovery-styles/package.json
We don't benefit much from doing independent versioning. storage space on npm in cheap -> remembering which packages go with each other is not.
This swaps out our versioning process from `independent` to the default `fixed` versioning. lerna will manually go through and update the `lerna.json` and various `package.json` files after a release.
run `npx lerna version --allowBranch remove_independent_versioning` to validate that versions for all packages are kept in sync (seems like the `styles` was out of sync)
N/A
N/A
> chore: remove independent versioning

- packages/discovery-react-components/src/components/SearchResults/SearchResults.tsx
- packages/discovery-react-components/src/components/SearchResults/components/Result/Result.tsx
- packages/discovery-react-components/src/components/SearchResults/components/Result/__tests__/Result.test.tsx
This PR handles and adds a callback - `handleSelectedResult` and pass document, so that `document` will be readily available when the user clicks on "view passage in document" etc.
Helps fixes: https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/1239
Link this and test PR: https://github.ibm.com/Watson-Discovery/discovery-tooling/pull/7356
No
> fix: add a callback - handleSelectedResult to SearchResults

- packages/discovery-react-components/src/utils/getDocumentTitle.ts
Changing "Select field to display as titles" didn't work for nested object values even though the value was available in the json
Link react component with discovery tooling, run the app and follow these steps:
1- got to Simple Document and search for Pak.
2- On the Improvement tools panel, select Customize display, then choose Search results. In the Select field to display as titles, choose extracted_metadata.file_type from the drop-down 
The document identifier in each search result should switch from the document name to the file type, this is broken on tooling right now.
No
> fix: select field to display as title

- examples/discovery-search-app/cypress/integration/dynamic_facets/spec.ts
- examples/discovery-search-app/cypress/integration/multi_select_facets/spec.ts
- examples/discovery-search-app/cypress/integration/single_select_facets/spec.ts
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/CollapsibleFacetsGroup.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/MultiSelectFacetsGroup.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/SingleSelectFacetsGroup.tsx
- packages/discovery-react-components/src/components/SearchFacets/messages.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/searchFacetInterfaces.ts
Adds the number of found documents to each search facet label. The search facets are ordered in descending order. Does not show a count for Dynamic Facets as those are not supported by the API yet.
https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/911
- Run `yarn storybook` inside `discovery-react-components`, click on Search Facets and see the document counts are now there.
- Or link components to `discovery-tooling` and see the search facets now have result counts.
Cypress tests in the example app have been updated.
No
> fix: add result count to search facets

- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/CollapsibleFacetsGroup.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/FieldFacets.test.tsx
Updates failing Jest tests to include searchFacet counts in the labels.
Run `yarn test` in `discovery-react-components`
No
> fix: fix jest tests for searchFacets change

- packages/discovery-styles/scss/components/search-input/_search-input.scss
- packages/discovery-styles/scss/components/search-results/_search-results.scss
- packages/discovery-styles/scss/index.scss
https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/1408
Carbon component dependency outside example app
1. [Setup create react app](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app
) 
2. Pull down this PR.
3. Follow steps https://github.com/watson-developer-cloud/discovery-components#using-discovery-components-in-a-react-application to setup stuff. 
4. Under create-react-app -> cd node_modules/react -> yarn link
5. Under components repo -> discovery-react-components -> yarn link "react" (react version match needed)
6. Under components repo  run `yarn link` under `discovery-react-components` and ` discovery-styles`
7. Under create-react-app -> yarn link "@ibm-watson/discovery-react-components"  & yarn link "@ibm-watson/discovery-styles"
8. Under …
> fix: carbon component dependency outside example app

- README.md
Following "Using Discovery Components in React" steps results in a compile error. There was previously another error resolved by [1408](https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/1408), this was an error uncovered after that. 
This also changes the default code snippet so that if a user does not replace all the variables, they will not see en error page but rather a message with instructions.
1. Follow steps in https://github.com/watson-developer-cloud/discovery-components#using-discovery-components-in-a-react-application
2. See error:
```Module not found: Can't resolve 'carbon-icons' in '.../create-react-app/node_modules/carbon-components-react/es/components/Icon'```
3. Follow steps now documented in this PR.
4. See that project compiles.
5. See that message …
> fix: readme setup steps

- examples/discovery-search-app/cypress/integration/collection_filter/spec.ts
This fixes the two failing cypress tests in `collection_filter` that are preventing the current master from building. 
I had to change the alias name in both tests since a describe that wraps these was using the same alias name. Not sure how the original test ever worked.
run `yarn cypress` and see that all tests now pass
N/A
No
> fix: failing cypress test

- examples/discovery-search-app/cypress/integration/collection_filter/spec.ts
- packages/discovery-react-components/src/components/DiscoverySearch/DiscoverySearch.tsx
- packages/discovery-react-components/src/components/SearchFacets/__fixtures__/configuration.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/__tests__/buildAggregationQuery.test.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/buildAggregationQuery.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/searchFacetInterfaces.ts
During Integration Testing for the grouping top entities issue, Laxmi caught that dictionary aggregations (`nested` and `filter`) were causing an error. This is because their configuration wasn't checked for in the `buildAggregationQuery`. I've updated to check for them and build the query according to their configuration(s) as well.
Link these changes with Tooling and run against a project that includes dictionary facets. For example, there are two set up on `weary-griffin` at this time in the Sample project, if they're still there during testing. See that the expected facets render without error when searching. Check network requests and confirm that what is expected to be sent/received from the `query` endpoint is.
no
no
> fix: buildAggregationQuery should work with dictionary (nested and filter) aggregations

- packages/discovery-react-components/src/components/SearchFacets/__fixtures__/facetsQueryResponse.ts
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/CategoryFacets.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/CollapsibleFacetsGroup.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/MultiSelectFacetsGroup.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FieldFacets.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/ShowMore/EmptyModalState.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/ShowMore/ModalSearchInput.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/ShowMore/ShowMoreButton.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/ShowMore/ShowMoreModal.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/CollapsibleFacetsGroup.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/FieldFacets.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/constants.ts
- packages/discovery-react-components/src/components/SearchFacets/messages.ts
- packages/discovery-styles/scss/components/search-facets/_search-facets.scss
This PR is based off of Kathryn's modal PR. This implements a search bar in the modal for when there are more than 15 facets. The search is case insensitive.
- Run storybook with `yarn storybook`. See that the modal under `Products` contains the search bar. Play around with it and see that it behaves as expected. To see a modal without the search bar, got to `Quantity`.
- Link to tooling. Create a facet with more than 15 fields (I usually do `extracted_metadata.filename`). See the modal with a search bar appears when you click `See all`. Play with the modal and see it works as expected.
- Check that tests are everything we want.
Tests have been updated.
No
> feat: add search bar to facet modal

- packages/discovery-react-components/src/components/SearchFacets/__fixtures__/facetsQueryResponse.ts
- packages/discovery-react-components/src/components/SearchFacets/__stories__/SearchFacets.stories.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/DynamicFacets.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/CollapsibleFacetsGroup.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/ShowMore/ModalSearchInput.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/ShowMore/ShowMoreModal.tsx
Fixes a bug found during integration testing for the Dynamic Facets modal.
- Modal was only applying the first selection for Dynamic Facets
- Modal search bar was not reloading the Dynamic Facet list upload clearing the entry
This is because Dynamic Facets are handled slightly differently than all other facets. The fixes now account for that.
This also includes a small change to add a tag to SingleSelect facets so that users know when one is selected without having to open the modal.
Run `yarn storybook` and click on `Show all` for the Dynamic Facets. See that the modal now behaves correctly.
No
> fix: dynamic search facets modal

- .github/CODEOWNERS
Adds @broulaye  as a codeowner, since @noah-eigenfeld is moving to support for a six-week rotation (and @kabeaty is out on parental leave).
> Add Broulaye to CODEOWNERS

- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/CategoryFacets.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/CollapsibleFacetsGroup.test.tsx
Fixes a one off error inside the CategoryFacets so that they show up to 5 facets when `show more` is added. It was previously showing 4 and was inconsistent with the other facets.
Issue: https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/1545
- Run storybook **without** the change in `CategoryFacets.tsx`
- See that the CategoryFacet `Locations` and `Quantity` only have 4 facets
- See `Products`, `Machine Learning`, and `Dynamic Facets` have 5 facets
- See that the added test fails
- Add back the change and run storybook
- See that both `Locations` and `Quantity` have 5 facets
- See that the added test passes
Tests have been updated
No
> fix: category facet not showing correct number

- packages/discovery-react-components/src/components/SearchFacets/utils/__tests__/buildAggregationQuery.test.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/buildAggregationQuery.ts
Changes the aggregation request for Top Entities so that it uses `nested`. Doing this allows for more accurate categories in the response.
issue: https://github.ibm.com/Watson-Discovery/the-tooling-core-tracker/issues/1579
**Before:**
**After:**
1. Go to https://zen-25-cpd-zen-25.apps.weary-griffin-master-1.fyre.ibm.com/discovery/core/instances/00000000-0000-0000-0001-590585699206/projects/1b62db48-f7b4-449c-9702-f22e3bebb4a2/workspace
2. See the facets appear as the before picture above.
3. Link this PR to tooling by running `yarn link-components` in `tooling`.
4. Go back to the `Throw away your television` project on `weary-griffin` and see that the categories match the after image above.
Tests have been updated
No
> fix: improve query for Top Entities

- packages/discovery-react-components/src/components/DocumentPreview/components/HtmlView/HtmlView.tsx
- packages/discovery-react-components/src/components/SearchResults/components/Result/Result.tsx
- packages/discovery-react-components/src/components/SearchResults/components/ResultElement/ResultElement.tsx
- packages/discovery-react-components/src/components/SearchResults/messages.ts
Table results are unable to be read by screen readers. For now, we are going to mark them as "presentation" so that the screen readers don't incorrectly them. We will follow up with a better solution that attempts to add headers to the data if they are available.
1. Run linked to tooling against cloud
2. Select a project with table results
3. When the results are returned in the search, and have a table in them run the [IBM Equal Accessibility Checker](https://chrome.google.com/webstore/detail/ibm-equal-access-accessib/lkcagbfjnkomcinoddgooolagloogehp) to verify it doesn't read the tables
No
> fix: updating rendering of html to add role presentation to tables

- packages/discovery-react-components/src/components/SearchResults/components/ResultElement/ResultElement.tsx
- packages/discovery-react-components/src/utils/document/processDoc.ts
Improves the accessibility for table results, because the `article` allows the screen reader to still read table. However it will not attempt to read the table like an actually table.
The goal of these tables in the results is to allow the user to verify that the result is what they are looking for, and not to display an exact replica of the table from the document.
1. Run linked to tooling against cloud
2. Select a project with table results
3. When the results are returned in the search, and have a table in them run the IBM Equal Accessibility Checker to verify it doesn't read the tables
N/A
No
> fix: wrapping tables in article role

- packages/discovery-react-components/src/components/DocumentPreview/DocumentPreview.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/SimpleDocument/SimpleDocument.tsx
Noticed when cleaning up tooling tests that were were getting the following error:
```
console.error src/setupTests.js:107
Warning: Cannot update a component (`DocumentPreview`) while rendering a different component (`SimpleDocument`). To locate the bad setState() call inside `SimpleDocument`, follow the stack trace as described in https://fb.me/setstate-in-render
in SimpleDocument (created by PreviewDocument)
in PreviewDocument (created by DocumentPreview)
in div (created by DocumentPreview)
in div (created by DocumentPreview)
in DocumentPreview (created by WithErrorBoundary(DocumentPreview))
in WithErrorBoundary(DocumentPreview) (at DocumentDetails.js:205)
in LazyLoadContent (at TabContentRenderedOnlyWhenSelected.tsx:46)
in div (at TabContentRenderedOnlyWhenSelected.tsx:40)
in …
```
> fix: some bad set states in Document components

- packages/discovery-react-components/src/components/SearchFacets/SearchFacets.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/CollapsibleFacetsGroup.tsx
This adds an event callback for toggling collection facets that can be used for event tracking.
Companion tooling PR: https://github.ibm.com/Watson-Discovery/discovery-tooling/pull/7655
Pull down the tooling PR branch and use `yarn link-components` to test changes.
In a project workspace (sample project is fine), perform any search.  Select a collection facet, and see in the console a list of selected collection facets.
> fix: add collections facets hook for event tracking

- packages/discovery-react-components/src/components/DocumentPreview/components/Highlight/passages.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/HtmlView/HtmlView.tsx
- packages/discovery-styles/scss/_vars.scss
- packages/discovery-styles/scss/components/document-preview/_document-preview-html.scss
- packages/discovery-styles/scss/components/document-preview/_document-preview.scss
- packages/discovery-styles/scss/components/document-preview/_simple-document.scss
Fix how highlighting is handled:
1. Fix issue where if offset had value of zero, highlight was ignored.
2. If background-color was applied, then highlights in HTML docs disappeared (z-index issue).
This also updates the CSS for highlights rects in `SimpleDocument` to match the implementation in `HtmlView`.
To verify fix (1):
1. Start storybook and load **DocumentPreview > passage highlighting**
2. Using React Dev Tools plugin, select the `HtmlView` component
3. In box at upper-right (labeled "props"), update the `highlight` property to have `end_offset` of 20 and a `start_offset` of 0.
4. Notice that highlight properly renders
To verify fix (2):
1. In same storybook, go to **Inspector > Elements** and select the node `<div class="bx--document-preview">`
2. Add style of `background-color: …
> fix: html highlighting

- examples/discovery-search-app/src/app.scss
- packages/discovery-styles/scss/components/ci-document/_ci-document-content.scss
- packages/discovery-styles/scss/components/ci-document/_ci-document-details.scss
- packages/discovery-styles/scss/components/ci-document/_ci-document-filter.scss
- packages/discovery-styles/scss/components/ci-document/_ci-document-metadata-pane.scss
- packages/discovery-styles/scss/components/ci-document/_ci-document-section.scss
- packages/discovery-styles/scss/components/ci-document/_ci-document-toolbar.scss
- packages/discovery-styles/scss/components/ci-document/_ci-document-virtual-scroll.scss
- packages/discovery-styles/scss/components/ci-document/_ci-document.scss
- packages/discovery-styles/scss/components/document-preview/_document-preview-toolbar.scss
- packages/discovery-styles/scss/components/document-preview/_document-preview.scss
- packages/discovery-styles/scss/components/document-preview/_simple-document.scss
- packages/discovery-styles/scss/components/search-facets/_search-facets.scss
- packages/discovery-styles/scss/components/search-input/_search-input.scss
- packages/discovery-styles/scss/components/search-results/_search-results.scss
- packages/discovery-styles/scss/components/structured-query/_structured-query.scss
This PR updates tooling to use the correct carbon 10 vars. Luckily there was a 1:1 mapping, so this PR is a find and replace.
I decided to hold off on the layout migration for this PR since the file count is going to be large here.
References:
https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/globals/scss/migrate-to-10.x.md#_spacingscss
https://www.carbondesignsystem.com/guidelines/spacing/overview/#spacing-scale
All components should retain the same padding and margins as before.
No.
No
> refactor: carbon spacing tokens

- examples/discovery-search-app/package.json
- package.json
- packages/discovery-react-components/.storybook/webpack.config.js
- packages/discovery-react-components/package.json
- packages/discovery-react-components/src/components/CIDocument/components/CIDocument/__stories__/CIDocument.stories.tsx
- packages/discovery-react-components/src/components/DiscoverySearch/DiscoverySearch.tsx
- packages/discovery-react-components/src/components/DiscoverySearch/__tests__/DiscoverySearch.test.tsx
- packages/discovery-react-components/src/components/DiscoverySearch/types.ts
- packages/discovery-react-components/src/components/SearchResults/utils/findCollectionName.ts
- packages/discovery-react-components/src/utils/__tests__/deprecation.test.ts
- packages/discovery-react-components/src/utils/__tests__/useDataApi.test.tsx
- packages/discovery-react-components/src/utils/deprecation.ts
- packages/discovery-react-components/src/utils/useDataApi.ts
- yarn.lock
`axios` had a vulnerability in one of our packages (`ibm-watson`) so we needed to upgrade that. Unfortunately since we had to go up a major version to get it (we were on `alpha`), we had breaking changes detailed in https://github.com/watson-developer-cloud/node-sdk/wiki/v5-Migration-Guide#discovery
- `returnFields` was renamed to `_return`, we added a deprecation warning to anyone who uses this library and still has `returnFields` but copies it over to `_return` while logging a warning.
- `prefix` became required on the `GetAutocompleteParameters` type
Also took the time to clean up some types for `useDataApi` utility and `DiscoverySearch` component to more closely align with reality without breaking any public APIs
`lerna run test`
TBD
no breaking change until next major version
> fix: Upgrade watson sdk

- packages/discovery-react-components/src/components/DiscoverySearch/DiscoverySearch.tsx
- packages/discovery-react-components/src/components/SearchFacets/SearchFacets.tsx
- packages/discovery-react-components/src/components/SearchFacets/__tests__/SearchFacets.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/utils/searchFacetInterfaces.ts
- packages/discovery-react-components/src/utils/__tests__/useDataApi.test.tsx
- packages/discovery-react-components/src/utils/testingUtils.tsx
- packages/discovery-react-components/src/utils/useDataApi.ts
Updates how we utilize `fetchGlobalAggregations` to handle cases when the response errors to not enter an infinite loop
`./runExampleApp.sh` and validate that after setting proper config it doesn't freeze your browser on `/query` 404 errors
N/A
N/A
> refactor: change usage of fetchGlobalAggregations

- .github/workflows/ci.yaml
- README.md
`~/.npmrc` doesn't like `registry=` -> removing that to see if publishing works now
> ci: fix publishing

- .github/workflows/ci.yaml
lerna was still reporting `Assuming all packages changed` which indicates it doesn't have access to the diffs to compute whether a new version needs to be released
publish job on `master` succeeds
> ci: add fetch-depth

- examples/discovery-search-app/scripts/serverSetup.sh
updates the example app's `serverSetup.sh` to retrieve the proper API url
addresses https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/3319
`./runExampleApp.sh` and validate no more 404 errors (if you get all the configuration correct)
N/A
N/A
> fix: setup script

- examples/discovery-search-app/cypress/integration/multi_select_facets/spec.ts
- examples/discovery-search-app/cypress/integration/single_select_facets/spec.ts
We don't need to separate out different assertions in our Cypress tests with their own `beforeEach`. This makes tests run slower and I think is part of the cause of the flakiness we're seeing. See Cypress best practices around this, too: https://docs.cypress.io/guides/references/best-practices.html#Creating-%E2%80%9Ctiny%E2%80%9D-tests-with-a-single-assertion
See that the build has passed (could be lucky too, so see how it helps going forward).
> test: group assertions together in Cypress tests

- .github/workflows/ci.yaml
- packages/discovery-react-components/src/components/DiscoverySearch/DiscoverySearch.tsx
- packages/discovery-react-components/src/components/DiscoverySearch/__tests__/DiscoverySearch.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/SearchFacets.tsx
- packages/discovery-react-components/src/utils/__tests__/useDataApi.test.tsx
- packages/discovery-react-components/src/utils/useDataApi.ts
need to prevent setting the searchParameters for the search response store when doing aggregation fetches. this was setting the count to `0` due to defaults
`/runExampleApp.sh` and perform a bunch of searches (empty) and validate you continue to get results back (albeit slow ones at times)
No
No
> fix: do not set count on search params for fetchAggregations

- packages/discovery-react-components/src/components/DiscoverySearch/DiscoverySearch.tsx
- packages/discovery-react-components/src/utils/__tests__/useDataApi.test.tsx
- packages/discovery-react-components/src/utils/useDataApi.ts
This adds the `error` encountered to the state in `useDataApi`. This is so that it can be used in Discovery tooling.
Check that the tests look good. Can link with tooling and run tests added with the related changes there too.
no
> feat: add error to dataapi

- .github/workflows/ci.yaml
As part of enabling 2FA for our NPM bot account, we generated an [automation token](https://github.blog/changelog/2020-10-02-npm-automation-tokens/) to continue allowing CI perform the publishing
Unfortunately, `lerna` uses a different API to verify that the token has access to publish that the automation tokens do not have. See https://github.com/lerna/lerna/issues/2788 for more details
> ci: no verify access on lerna publish

- .github/workflows/ci.yaml
- README.md
- lerna.json
Simplifies the release logic to always publish from `master` and no longer have `beta` or `rc` dist tags. Should generate changelogs + github releases based on conventional commits syntax
downsides include not knowing which version of these packages match with which versions of cp4d deployments of discovery
`npx lerna publish --no-git-tag-version --no-push --create-release github`
^ should do all the steps necessary without making changes to the npm package or pushing to github
Yes
No
> build: simplify release automation

- docs/components/custom_components.md
Escape code section containing double curly braces, since these are used by the Liquid templating language:
> docs: escape double curly braces

- examples/discovery-search-app/cypress/integration/pagination/spec.ts
- package.json
- packages/discovery-react-components/package.json
- packages/discovery-react-components/src/components/CIDocument/components/CIDocument/__fixtures__/shortenedContract.json
- packages/discovery-react-components/src/components/ResultsPagination/ResultsPagination.tsx
- packages/discovery-react-components/src/components/ResultsPagination/__tests__/ResultsPagination.test.tsx
- packages/discovery-react-components/src/components/ResultsPagination/messages.ts
- packages/discovery-styles/scss/carbon-components.scss
- packages/discovery-styles/scss/components/results-pagination/_results-pagination.scss
- yarn.lock
Carbon's `Pagination` component does not work well if there are a large number of items, resulting in app hanging or crashing (see https://github.com/carbon-design-system/carbon/issues/5546).
This PR changes us to use the "unstable" `Pagination` component from Carbon, which will get promoted to the official one in Carbon v11. By doing so, this no longer renders a select control to pick the current page (which is of dubious usability for search results), and avoids the performance issue.
New component:
Easiest way to see the underlying issue is to load https://react.carbondesignsystem.com/?path=/story/components-pagination--pagination and enter a large number like `400000` for `totalItems` (in "Knobs" tab at bottom of page). Browser page will hang.
To see fix, run our Storybook with this …
> fix: use "unstable" Carbon Pagination to avoid performance hang

- packages/discovery-react-components/src/components/SearchFacets/components/CollectionFacets.tsx
- yarn.lock
The IBM accessibility checker found a violation in our CollectionFacet component. The dropdown element said it was labeled, but no element with that id existed in the dom. Turns out, Carbon already had a property built into the component that would do that for us. So, I removed our custom label elements and passed the text into that property.
This component before (on Storybook, so ignore the background color change):
This component after:
There did appear to be a slight font color change along with this, but it's not setting off any additional a11y violations, and in my mind this will most likely unify us across other Carbon components within Tooling. If someone yells at me, though, I can try to change the text color back.
1. Run the example app
2. Run the accessibility checker (install …
> fix: use carbon's built-in label for MultiSelect

- packages/discovery-react-components/src/components/SearchFacets/__fixtures__/configuration.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/__tests__/buildAggregationQuery.test.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/__tests__/escapeFieldNames.test.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/buildAggregationQuery.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/escapeFieldName.ts
- packages/discovery-react-components/src/index.tsx
Certain characters are not supported for field names when generating an aggregation string -- if present, will result in a query error. Escape field names to prevent such a failure.
Implements https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/8437
Run tests
> fix: escape field names before building aggregation string

- packages/discovery-react-components/src/components/SearchFacets/utils/__tests__/escapeFieldNames.test.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/escapeFieldName.ts
Safari doesn't support regex lookbehind (https://caniuse.com/js-regexp-lookbehind). Use JS instead to determine if a character has already been escaped.
Implements https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/8709
- Run tests.
- Link into Tooling and load in Safari
> fix: safari regex lookbehind

- runExampleApp.sh
Add quotes for file paths in order to handle directories with spaces.
Fixes #187
1. If you've cloned this repo into a dir named `discovery-components/`, rename that dir to `discovery components`.
2. Run `./runExampleApp.sh` without this PR. Notice it throws errors at certain lines.
3. Re-run with this PR. Will now succeed.
> fix: add quotes for file paths

- examples/discovery-search-app/cypress/integration/multi_select_facets/spec.ts
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/FieldFacets.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/utils/__tests__/searchFilterTransform.test.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/searchFilterTransform.tsx
Implements: https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/9339
Fixes the default logic assembling query filter string anytime that facets are applied to a search.
~This change should add parens ( ) around the values for any fields in the filter param. That way, if there are multiple values for one facet, they are correctly bundled together. Hopefully, it should look something like `facet-name:("value1"|"value2"|"value3"),facet-2-name:("value4"), . . .`.~
The parens I tried to add were getting stripped out by a followup step that gets rid of special characters. Instead, I opted to stack the facet-name/value pairs. They should now look like this:
```
filter: facet-name:"value1"|facet-name:"value2"|facet-name:"value3",facet-2-name:"value4", . . .
```
1. Start the example …
> fix: correct query filter string generation

- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewer.tsx
From #229, moved the source to a local branch. 
When you specify `scale` props to `PdfViewer` componenet, the PDF image on the screen scales by the square of the `scale` value.
For example, when you specify `1.5` to the value, the width of the image gets `1.5 * 1.5 = 2.25` times of the original. That's because the `canvas` size is determined with `scale` and the `scale` is again used to scale the `canvas` by `scale`.
Use an existing storybook.
no
> fix: PdfViewer scale parameter issue

- yarn.lock
Fix build error caused after merging #237
https://github.com/watson-developer-cloud/discovery-components/runs/4426288121?check_suite_focus=true
```
YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
```
Successful CI build.
N/A
No
> fix: fix build error

- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewerHighlight/PdfViewerHighlight.tsx
- yarn.lock
On PDFViewer with highlight, after you switch PDF pages, highlights on PDF gets misaligned.  This PR is to fix it.
In the screenshot, `documented acceptance` should be highlighted, but not in PDF view.
**Steps**
1. Open the storybook
2. Select the `documented acceptance` in the right pane. The text is highlighted on PDF
3. Move to page 2 using Knob
4. Move page back to 1
5. You see misaligned highlight
The issue comes from incorrect dependencies of a React hook. Also, the calculation of highlight rectangle starts before all the data is gathered.
Run the scenario using the storybook. Highlight shouldn't be misaligned even after moving pages back and force.
N/A
No
> fix: fix PDF highlight misalignment issue

- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewerHighlight/utils/Highlighter.ts
- yarn.lock
Highlighting on PDF could be overlapped or segmented for a single span. The following screenshots shows them.  It depends on how _text content items_ are stored in PDF. This PR is to fix them by merging highlight boxes next to each other.
**overlapped**
**segmented** in a line even when highlighting a single span.
Please use the storybook to verify this. Select various text ranges in the _PdfViewerWithHighlight/with text selection_ storybook.
N/A
No
> fix: mitigate overlapped or segmented highlight on PDF

- packages/discovery-react-components/src/components/DiscoverySearch/types.ts
- yarn.lock
Add `result_metadata` prop type to `DocumentProviderProps` interface
> fix: add missing prop to doc provider interface

- packages/discovery-react-components/src/components/DocumentPreview/DocumentPreview.tsx
- packages/discovery-react-components/src/components/DocumentPreview/__stories__/DocumentPreview.stories.tsx
- packages/discovery-react-components/src/components/DocumentPreview/types.ts
- packages/discovery-react-components/src/components/DocumentPreview/utils/__tests__/documentData.test.ts
- packages/discovery-react-components/src/components/DocumentPreview/utils/documentData.ts
- yarn.lock
Currently, there's small gap with the type (PDF/HTML/TEXT) of the preview displayed for a document in `DocumentPreivew`. Specifically, when we have a PDF file and a passage, but not `text_mappings`, the TEXT view is expected.
To fix the behavior,
- I extracted a function for determining preview type, then
- Make the function work as expected.
- I also added the scenario to the storybook
Please use the updated storybook, and check if new tests in CI passes
n/a
no
> fix: fix preview type displayed in DocumentPreview

- packages/discovery-react-components/.storybook/styles.scss
- packages/discovery-react-components/src/components/DocumentPreview/components/PreviewToolbar/PreviewToolbar.stories.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PreviewToolbar/PreviewToolbar.tsx
- packages/discovery-react-components/src/components/DocumentPreview/messages.ts
- packages/discovery-styles/scss/components/document-preview/_document-preview-toolbar.scss
Update the PDFViewer's toolbar design to match the latest UX.
- Use up/down icon for PDF pagenation
- Add capability of adding `pages` suffix after the number of pages
- Add capability of putting user-defined widget into the toolbar
- Use DocumentPreview/components/PreviewToolbar/default story http://localhost:9002/?path=/story/documentpreview-components-previewtoolbar--default
no
no
> feat: update PDFViewer toolbar style

- packages/discovery-react-components/src/components/DocumentPreview/components/HtmlView/HtmlView.tsx
- yarn.lock
Eliminate the following console out on showing `DocumentPreview`.
```
Warning: Cannot update a component (`DocumentPreview`) while rendering a different component (`HtmlView`). To locate the bad setState() call inside `HtmlView`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
at HtmlView (http://localhost:9002/main.39ae2b585ef0315cf79f.bundle.js:5019:23)
at PreviewDocument (http://localhost:9002/main.39ae2b585ef0315cf79f.bundle.js:4415:19)
at div
at div
at DocumentPreview (http://localhost:9002/main.39ae2b585ef0315cf79f.bundle.js:4339:23)
at WithErrorBoundary (http://localhost:9002/main.39ae2b585ef0315cf79f.bundle.js:16154:36)
```
- Open "Document Preview / default" storybook,
- Clear console, and then reload the window
- Verify that the warning message …
> fix: fix console error on showing DocumentPreview component

- packages/discovery-react-components/package.json
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewer.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewerWithHighlight/PdfViewerWithHighlight.stories.tsx
- yarn.lock
Fix #314 . Reset canvas' transformation before drawing PDF page to fix https://github.com/watson-developer-cloud/discovery-components/issues/314#issuecomment-1055055545.
The issue can be reproduced by switching pages quickly. I added a new storybook `DocumentPreview / components / PdfViewerWithHighlight / with user's PDF and JSON` so that we can test PDF viewer using user-provided PDF and JSON.
You can use the story to test a problematic PDF.
no
> fix: fix broken pdf rendering

- packages/discovery-react-components/src/components/DocumentPreview/DocumentPreview.tsx
- packages/discovery-react-components/src/components/DocumentPreview/__stories__/DocumentPreview.stories.tsx
- yarn.lock
This PR is to add `onPreviewStateChange` event to the `DocumentPreview` component so that its parent component can be notified with the preview state changes.
I added an storybook action to the DocumentPreview storybooks. Switch to the Actions tab in the bottom pane and see if the state change event is logged.
> feat: add state change event to DocumentPreview component

- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewerWithHighlight/PdfViewerWithHighlight.stories.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewerWithHighlight/PdfViewerWithHighlight.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewerWithHighlight/__tests__/useMovePageToActiveHighlight.test.ts
- yarn.lock
This PR is to fix the following issues related to page switching in PdfViewer with highlights.
- When PDF viewer is initially shown with active highlight, the first page change (for example,  by user's clicking on Next page button) is ignored
- Fixed by improving logic of page change. The condition of setting page was wrong.
- Suppose that PDF viewer is initially shown with active highlight, and user moves the current page. When user tries to activate another highlight on the same page to the initially activated highlight, the newly activated highlight is not revealed. Instead, PDF viewer keep showing the same page. 
- The internal logic tracked only page number of an active highlight. So it couldn't detect changes of active highlight  when the highlights are on the same page. Now the …
> fix: fix page switching issue with PdfViewerWithHighlight

- .eslintrc
- README.md
- examples/discovery-search-app/cypress/integration/basic/spec.ts
- examples/discovery-search-app/src/App.js
- examples/discovery-search-app/src/app.scss
- packages/discovery-react-components/src/components/DiscoverySearch/DiscoverySearch.tsx
- packages/discovery-react-components/src/components/DiscoverySearch/__tests__/DiscoverySearch.test.tsx
- packages/discovery-react-components/src/components/DocumentPreview/__tests__/DocumentPreview.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/DynamicFacets.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/CollapsibleFacetsGroup.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FacetsGroups/MultiSelectFacetsGroup.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/FieldFacets.tsx
- packages/discovery-react-components/src/components/SearchResults/SearchResults.tsx
- packages/discovery-react-components/src/components/SearchResults/__tests__/SearchResults.test.tsx
- packages/discovery-react-components/src/components/SearchResults/utils/getDisplaySettings.ts
- packages/discovery-react-components/src/utils/__tests__/useDataApi.test.tsx
- packages/discovery-react-components/src/utils/useDataApi.ts
- packages/discovery-react-components/src/utils/useDeepCompareMemoize.ts
- packages/discovery-styles/package.json
- packages/discovery-styles/scss/components/ci-document/_ci-document.scss
- yarn.lock
Update `SearchResults` component to update the search parameters and limit the size of the response, to only what is needed to render `SearchResults`.
Update `fetchDocuments()` to take collection ID argument. Fix how response is merged into search store response.
Fix some eslint warnings.
Run example app and run a blank search. Note the size of the `/query` response before and after. Ensure that loading a document shows all document data.
Yes. See comments below.
> feat: limit response size

- packages/discovery-react-components/src/components/DocumentPreview/DocumentPreview.tsx
- packages/discovery-react-components/src/components/DocumentPreview/utils/__tests__/documentData.test.ts
- packages/discovery-react-components/src/components/DocumentPreview/utils/documentData.ts
Render TEXT when given an HTML file with passage to highlight (which only works on text, when there is no `text_mappings` to map to HTML-based offsets).
Run example app against a collection of web-crawled HTML files, where SDU model is default text-only.
---
> fix: render correct doc to show passage highlights

- packages/discovery-react-components/src/components/DocumentPreview/DocumentPreview.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewer.tsx
- Implements the following [issue](https://github.ibm.com/watson-discovery/disco-issue-tracker/issues/11135)
- allows disabling `textLayer` rendering
- use `Storybook` within the issue it implements to verify that `textLayer` is NOT rendered 
- use `Storybook` within the `discovery-components` to verify that `textLayer` is rendered by default
> render textLayer optionally

- examples/discovery-search-app/cypress/fixtures/query/tableResults.json
- examples/discovery-search-app/cypress/integration/tables/spec.ts
- packages/discovery-react-components/src/components/ResultsPagination/ResultsPagination.tsx
- packages/discovery-react-components/src/components/ResultsPagination/__tests__/ResultsPagination.test.tsx
- packages/discovery-react-components/src/components/SearchResults/SearchResults.tsx
- packages/discovery-react-components/src/components/SearchResults/__tests__/SearchResults.test.tsx
- packages/discovery-react-components/src/components/SearchResults/components/Result/Result.tsx
- yarn.lock
- Only include each document once in filter string
- Allow pagination to be reset externally
- No longer display table-only results with passage results
- No longer add page size to pagination options (if it wasn't already included)
- Use count values exclusively (ignore results_per_page)
Contributes to [Watson-Discovery/disco-issue-tracker#4145](https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/4145)
Run example app or against tooling
TO BE ADDED
Yes, see above.
> fix: Mitigate some pagination issues in search results

- packages/discovery-react-components/src/components/ResultsPagination/ResultsPagination.tsx
- yarn.lock
- rename the `ref` prop back to `resetRef` to allow it to be passed in properly
(Fix bug from https://github.com/watson-developer-cloud/discovery-components/pull/340#discussion_r922628853)
Contributes to [Watson-Discovery/disco-issue-tracker#4145](https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/4145)
Link to local tooling, make sure the resetRef prop is actually  getting populated (doesn't remain `undefined`).
Shouldn't need additional documentation.
No.
> fix: revert to renaming ref prop with forwardRef and HOC

- packages/discovery-react-components/src/components/SearchFacets/utils/searchFilterTransform.tsx
* Initially: searching returns no results when only facets are selected
* Using contain match query 
* Fix: showing results when facets are selected
* Using exact match query
Contributes to https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/12682
> fix: change the facet query method to exact match

- examples/discovery-search-app/cypress/integration/dynamic_facets/spec.ts
- examples/discovery-search-app/cypress/integration/multi_select_facets/spec.ts
- examples/discovery-search-app/cypress/integration/single_select_facets/spec.ts
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/CollapsibleFacetsGroup.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/DynamicFacets.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/FieldFacets.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/utils/__tests__/searchFilterTransform.test.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/searchFilterTransform.tsx
- yarn.lock
- revert exact match change
- group search phrases with parens to prevent query ambiguity
- escape more special characters
- fix unit and cypress tests
- fix build by updating version numbers in yarn.lock
Try the following on each of these two [staging](https://us-south.discovery.test.watson.cloud.ibm.com/v2/instances/crn%3Av1%3Astaging%3Apublic%3Adiscovery%3Aus-south%3Aa%2F24f453567f259b67c34ae38a6e6026fb%3A97732895-f1ad-4a2b-9951-548ee712f480%3A%3A/projects/918a1017-e178-4bc8-9b0e-a5950763ac16/workspace) / [local](http://localhost:4000/instances/crn%3Av1%3Astaging%3Apublic%3Adiscovery%3Aus-south%3Aa%2F24f453567f259b67c34ae38a6e6026fb%3A97732895-f1ad-4a2b-9951-548ee712f480%3A%3A/projects/918a1017-e178-4bc8-9b0e-a5950763ac16/workspace) (with this branch and linked to tooling)
1. Run an …
> fix: update tests from phrase query removal

- examples/discovery-search-app/cypress/integration/dynamic_facets/spec.ts
- examples/discovery-search-app/cypress/integration/multi_select_facets/spec.ts
- examples/discovery-search-app/cypress/integration/single_select_facets/spec.ts
- packages/discovery-react-components/src/components/CIDocument/components/CIDocument/__fixtures__/shortenedContract.json
- packages/discovery-react-components/src/components/CIDocument/components/CIDocument/__tests__/CIDocument.spec.tsx
- packages/discovery-react-components/src/components/CIDocument/components/CIDocumentContent/__fixtures__/contract.json
- packages/discovery-react-components/src/components/CIDocument/components/CIDocumentContent/__tests__/CIDocumentContent.spec.tsx
- packages/discovery-react-components/src/components/CIDocument/components/Section/__tests__/Section.spec.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/__tests__/PdfViewer.test.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/SimpleDocument/__tests__/SimpleDocument.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/CollapsibleFacetsGroup.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/CollectionFacets.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/DynamicFacets.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/components/__tests__/FieldFacets.test.tsx
- packages/discovery-react-components/src/components/SearchFacets/utils/__tests__/searchFilterTransform.test.ts
- packages/discovery-react-components/src/components/SearchFacets/utils/searchFilterTransform.tsx
- packages/discovery-react-components/src/components/SearchResults/__tests__/SearchResults.test.tsx
- packages/discovery-react-components/src/utils/document/documentUtils.ts
- packages/discovery-react-components/src/utils/document/processDoc.ts
- yarn.lock
- revert previous commit (changes were requested by Chris Cook [here](https://ibm-analytics.slack.com/archives/G0117CFBJTU/p1658509360115819?thread_ts=1658332780.760249&cid=G0117CFBJTU))
- re-add double quotes to query
- adjust query decoding to use '::'
- clean up test warnings and logs
Contributes to https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/12682
Try the following on each of these two [staging](https://us-south.discovery.test.watson.cloud.ibm.com/v2/instances/crn%3Av1%3Astaging%3Apublic%3Adiscovery%3Aus-south%3Aa%2F24f453567f259b67c34ae38a6e6026fb%3A97732895-f1ad-4a2b-9951-548ee712f480%3A%3A/projects/918a1017-e178-4bc8-9b0e-a5950763ac16/workspace) / [local](http://localhost:4000/instances/crn%3Av1%3Astaging%3Apublic%3Adiscovery%3Aus-south%3Aa%2F24f453567f259b67c …
> fix: revert previous facet changes and make new changes

- packages/discovery-react-components/package.json
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewer.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewerWithHighlight/PdfViewerWithHighlight.tsx
- packages/discovery-styles/scss/components/document-preview/_document-preview-pdf-viewer.scss
- packages/discovery-styles/scss/components/document-preview/_document-preview.scss
- yarn.lock
- Set initial canvas size based on the available width
- Adjust the size of the text layer and highlights proportionally
- Add ResizeObserver to adjust canvas accordingly when page is resized
Contributes to https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/12758
- Run UI locally linked with components repo running with this branch.
- Check that document highlighting, underlining, and boxing all align with PDF documents, regardless of zooming in and out
- Check that Storybook looks correct and that zooming works correctly for all stories
> fix: adjust how canvas dimensions are computed

- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewer.tsx
- packages/discovery-react-components/src/index.tsx
- packages/discovery-react-components/src/utils/useSafeRef.ts
- packages/discovery-react-components/src/utils/useSize.ts
- packages/discovery-styles/scss/components/document-preview/_document-preview-pdf-viewer.scss
- yarn.lock
- use the width of the bounding rectangle of the root ref, since useSize rounds up on half pixels
- Run Storybook, and check that PdfViewer stories are handling zooming and resizing properly and don't have unnecessary scrollbars
- Link to tooling and run tooling Storybook, and check that StructureView stories are handling zooming and resizing properly and don't have unnecessary scrollbars
> fix: prevent unnecessary horizontal scrollbar

- README.md
- package.json
- packages/discovery-react-components/package.json
- yarn.lock
- Replace `markdown-toc` (which is currently failing on `master` for unknown reasons) with `doctoc`. The former hasn't been updated in 5 years.
- Update several dependencies mentioned by Whitesource
> chore: upgrade deps

- examples/discovery-search-app/package.json
- packages/discovery-react-components/.storybook/main.ts
- packages/discovery-react-components/src/components/DocumentPreview/DocumentPreview.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewer.stories.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewer.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/__tests__/PdfViewer.test.tsx
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewerWithHighlight/PdfViewerWithHighlight.stories.tsx
- packages/discovery-react-components/src/setupTests.ts
- yarn.lock
- Add prop to send in a url for pdf.js worker
- Use this prop in the example app and Storybook
- Adjust tests accordingly
Yes, any use of the `PdfViewer` component (standalone, or as part of `PdfViewerWithHighlight`, `DocumentPreview` or `PreviewDocument` will need to supply a URL string to a hosted `pdf.js` worker file (e.g. https://github.com/mozilla/pdfjs-dist/blob/master/build/pdf.worker.min.js) via the `pdfWorkerUrl` prop.
> fix: finish updating pdfjs

- packages/discovery-react-components/src/components/SearchFacets/utils/searchFilterTransform.tsx
- yarn.lock
- Escape all double quotes (rather than just the first) using a global regex
> fix: escape all search filter double quote characters

- examples/discovery-search-app/.env
- examples/discovery-search-app/package.json
- yarn.lock
After upgrade to Webpack v5, we were seeing several warnings about relative import paths for SCSS/CSS files during the example app build. This PR uses an absolute path for SASS_PATH so we no longer get these warnings.
Run `yarn start` or `yarn build` for the example app
> build: set absolute SASS_PATH

- packages/discovery-react-components/src/components/DocumentPreview/components/HtmlView/HtmlView.tsx
Makes the `setLoading` callback optional on the `HtmlView` component. Also adds `style` to the list of tags being removed by DomPurify when Html is rendered. This should prevent global styles from leaking into the rest of the application.
A future task intends to do a better job with style handling, and should make user documents retain some of their style without leakage: https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/12210
n/a
n/a
no
> fix: make loading prop optional in HtmlView and fix style leaks

- packages/discovery-react-components/src/components/DocumentPreview/components/HtmlView/HtmlView.tsx
- yarn.lock
When we process an html document to render it in HtmlView -- as happens when there are highlights present -- we failed to strip all of the style elements, because they were getting manually added back outside the DOMPurify. This PR comments out that version of setting the html until we can sandbox the styling.
1. Link to tooling with the html view PR branch
2. Upload a pdf document and enable pre-trained sdu model
3. Query for the document, and view it in rich doc preview
4. See that the HTML View is correctly stripping style elements out of the rendered html
No
> fix: keep styles from leaking in html view when highlight present

- packages/discovery-react-components/src/components/CIDocument/components/CIDocumentContent/CIDocumentContent.tsx
- packages/discovery-react-components/src/components/CIDocument/types.ts
Contributes to https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/13113
in combination with https://github.ibm.com/Watson-Discovery/discovery-tooling/pull/9903
Reworks the prop we use to take in highlights with unique colors, such that we can display overlapping highlights with their own designated color
When activating a new highlight that overlaps with several of the highlights in the first screenshot:
1. Link components to tooling, and run locally
2. Find a project and document where facets exist with overlapping highlights (sample project often works for me)
3. Search for results in the above document, and toggle overlapping highlights on and off
a. When overlapping highlights are both activated, the entire highlights are displayed with Carbon's Purple-50 background
b. …
> feat: add styling for overlapping highlights in text view

- packages/discovery-react-components/src/components/TooltipHighlight/TooltipHighlight.tsx
- packages/discovery-styles/scss/components/document-preview/_document-preview-pdf-viewer.scss
Support feature enabled/ disabled as shown in screenshot
Discovery tooling, disable enhanced highlight feature
None
No
> fix: tooltip when facet available and border pdf active element

- examples/discovery-search-app/src/app.scss
to work around Chromium UI issue.
https://github.ibm.com/watson-discovery/disco-issue-tracker/issues/17308
Fixes a problem where the UI is shifted upwards after clicking checkboxes or radio buttons in the sample application.
**NOTE**: You may need to adjust your screen size to see the issue. I see the problem when the browser height is less than about 800 px.
- In the Discovery Tooling UI, create a Document Retrieval Contracts project.
- Add the Art Effects.pdf document located at \discovery-components\examples\discovery-search-app\public\documents\Art Effects.pdf. Wait for document processing to complete.
- Run the sample app in this repository, pointing to the project you created above.
- In the sample app, open the collection containing the Art Effects.pdf document, then click on the …
> fix: Add position: relative to checkboxes, radio buttons, and data table

- packages/discovery-react-components/src/components/SearchResults/components/Result/Result.tsx
- packages/discovery-react-components/src/utils/getDocumentTitle.ts
When using search, regardless of user query (empty or with actual strings), the message `There was an error rendering SearchResults`, when the code doesn't find document title where it is supposed to be. With this fix, it handles the case where title is its own separate field in the document with the format `"title": { "a": 1, "text": "title text" }`. If the field title is an object and doesn't have a field `text` in string format, just returns the `toString()` so that would result in displaying [object Object]. This would prevent the component from crashing.
Github issue: [16447](https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/16447)
1. Download [test.json.zip](https://github.ibm.com/Watson-Discovery/disco-issue-tracker/files/1174563/test.json.zip)
2. Unzip the file
3. …
> fix: fixed error in search results due to document title

- packages/discovery-react-components/package.json
- yarn.lock
Implementation for https://github.ibm.com/Watson-Discovery/disco-issue-tracker/issues/18222
Bumps the upper limit for react as a peer dependency of the components package. I think this should override the peer dependency in carbon components' 10/7 branch. React 18 shouldn't break anything functionally, but this change allows an app consuming discovery components and using react 18 to build successfully.
1. Checkout this branch locally, run `yarn` to install the latest package changes
2. Run `yarn why react` and see that the components themselves are still pulling in react 17
3. In the components package directory, run `yarn dlx yalc publish --push` to create a build and push it to a local repository that's linkable in tooling.
1. If the build fails here, you may need to delete …
> chore: bump react peerDep to include react 18

- packages/discovery-react-components/src/components/DocumentPreview/components/PdfHighlight/utils/Highlighter.ts
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfHighlight/utils/textLayout/PdfTextContentTextLayout.ts
- packages/discovery-react-components/src/components/DocumentPreview/components/PdfViewer/PdfViewerTextLayer.tsx
Return normalized `textDivs` and `textContent` values (to ensure that they match up with each other). These are passed to the `setRenderedText` callback. Fixes issue where highlights weren't properly positioned over PDF document.
> fix: return normalized text divs/content values
